on:
  pull_request:
      branches:
      - main

jobs:

  upload_files:
    runs-on: ubuntu-latest
    name: Update a theme files.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.IP }}
        port: 22
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}
        localPath: '.'
        remotePath: ${{ secrets.REMOTE_PATH }}     
      